// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=.js"
// @generated from file drill.proto (package waypoint.module.drill.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum waypoint.module.drill.v1.AugerDirection
 */
export enum AugerDirection {
  /**
   * @generated from enum value: AUGER_DIRECTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: AUGER_DIRECTION_IDLE = 1;
   */
  IDLE = 1,

  /**
   * conveys sample up the screw
   *
   * @generated from enum value: AUGER_DIRECTION_DRILL = 2;
   */
  DRILL = 2,

  /**
   * ratchet-engaged core rotation
   *
   * @generated from enum value: AUGER_DIRECTION_SWITCH = 3;
   */
  SWITCH = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(AugerDirection)
proto3.util.setEnumType(AugerDirection, "waypoint.module.drill.v1.AugerDirection", [
  { no: 0, name: "AUGER_DIRECTION_UNSPECIFIED" },
  { no: 1, name: "AUGER_DIRECTION_IDLE" },
  { no: 2, name: "AUGER_DIRECTION_DRILL" },
  { no: 3, name: "AUGER_DIRECTION_SWITCH" },
]);

/**
 * ---- backend -> tab: drill.state at the component rate ----
 *
 * @generated from message waypoint.module.drill.v1.DrillState
 */
export class DrillState extends Message<DrillState> {
  /**
   * @generated from field: google.protobuf.Timestamp t = 1;
   */
  t?: Timestamp;

  /**
   * Lift axis. Height is a software axis over multiple servo revolutions:
   * ticks need a home anchor, norm/mm need a calibrated travel span.
   *
   * @generated from field: bool homed = 2;
   */
  homed = false;

  /**
   * @generated from field: bool calibrated = 3;
   */
  calibrated = false;

  /**
   * unwrapped ticks below the top anchor; absent until homed
   *
   * @generated from field: optional int64 height_ticks = 4;
   */
  heightTicks?: bigint;

  /**
   * 0 = top .. 1 = bottom; absent until calibrated
   *
   * @generated from field: optional double height_norm = 5;
   */
  heightNorm?: number;

  /**
   * absent unless mm_per_tick configured
   *
   * @generated from field: optional double height_mm = 6;
   */
  heightMm?: number;

  /**
   * "unhomed" | "uncalibrated" | ""; explains the most-derived absent field
   *
   * @generated from field: string height_na_reason = 7;
   */
  heightNaReason = "";

  /**
   * last read PRESENT_SPEED, signed ticks/s
   *
   * @generated from field: optional sint32 lift_velocity_raw = 8;
   */
  liftVelocityRaw?: number;

  /**
   * Auger.
   *
   * @generated from field: waypoint.module.drill.v1.AugerDirection auger_direction = 9;
   */
  augerDirection = AugerDirection.UNSPECIFIED;

  /**
   * @generated from field: optional sint32 auger_velocity_raw = 10;
   */
  augerVelocityRaw?: number;

  /**
   * @generated from field: bool switch_allowed = 11;
   */
  switchAllowed = false;

  /**
   * "" when allowed; "uncalibrated" | "below top band" | "halted"
   *
   * @generated from field: string switch_refused_reason = 12;
   */
  switchRefusedReason = "";

  /**
   * Safety and activity.
   *
   * @generated from field: bool halted = 13;
   */
  halted = false;

  /**
   * "" | "stop command" | "input stale" | "read gap" | "overcurrent"
   *
   * @generated from field: string halt_reason = 14;
   */
  haltReason = "";

  /**
   * "idle" | "jog" | "goto" | "homing" | "calibrating"
   *
   * @generated from field: string phase = 15;
   */
  phase = "";

  /**
   * most recent refused command with reason, "" when none
   *
   * @generated from field: string last_refusal = 16;
   */
  lastRefusal = "";

  /**
   * Raw per-servo telemetry (lift = bus 11, auger = bus 12).
   *
   * @generated from field: waypoint.module.drill.v1.ServoState lift = 17;
   */
  lift?: ServoState;

  /**
   * @generated from field: waypoint.module.drill.v1.ServoState auger = 18;
   */
  auger?: ServoState;

  constructor(data?: PartialMessage<DrillState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "waypoint.module.drill.v1.DrillState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "t", kind: "message", T: Timestamp },
    { no: 2, name: "homed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "calibrated", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "height_ticks", kind: "scalar", T: 3 /* ScalarType.INT64 */, opt: true },
    { no: 5, name: "height_norm", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 6, name: "height_mm", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 7, name: "height_na_reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "lift_velocity_raw", kind: "scalar", T: 17 /* ScalarType.SINT32 */, opt: true },
    { no: 9, name: "auger_direction", kind: "enum", T: proto3.getEnumType(AugerDirection) },
    { no: 10, name: "auger_velocity_raw", kind: "scalar", T: 17 /* ScalarType.SINT32 */, opt: true },
    { no: 11, name: "switch_allowed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 12, name: "switch_refused_reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "halted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 14, name: "halt_reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 15, name: "phase", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 16, name: "last_refusal", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 17, name: "lift", kind: "message", T: ServoState },
    { no: 18, name: "auger", kind: "message", T: ServoState },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DrillState {
    return new DrillState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DrillState {
    return new DrillState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DrillState {
    return new DrillState().fromJsonString(jsonString, options);
  }

  static equals(a: DrillState | PlainMessage<DrillState> | undefined, b: DrillState | PlainMessage<DrillState> | undefined): boolean {
    return proto3.util.equals(DrillState, a, b);
  }
}

/**
 * ---- tab/teleop -> backend on drill.cmd ----
 *
 * @generated from message waypoint.module.drill.v1.DrillCommand
 */
export class DrillCommand extends Message<DrillCommand> {
  /**
   * @generated from oneof waypoint.module.drill.v1.DrillCommand.action
   */
  action: {
    /**
     * hold-to-move; velocity_norm 0 stops the lift
     *
     * @generated from field: waypoint.module.drill.v1.JogLift jog_lift = 1;
     */
    value: JogLift;
    case: "jogLift";
  } | {
    /**
     * requires calibrated
     *
     * @generated from field: waypoint.module.drill.v1.GotoHeight goto_height = 2;
     */
    value: GotoHeight;
    case: "gotoHeight";
  } | {
    /**
     * hold-to-move; throttle 0 stops the auger
     *
     * @generated from field: waypoint.module.drill.v1.RunAuger run_auger = 3;
     */
    value: RunAuger;
    case: "runAuger";
  } | {
    /**
     * halt latch: zero-write both, torque off, refuse motion until fresh input
     *
     * @generated from field: bool stop = 4;
     */
    value: boolean;
    case: "stop";
  } | {
    /**
     * creep up to stall, anchor top
     *
     * @generated from field: bool home = 5;
     */
    value: boolean;
    case: "home";
  } | {
    /**
     * @generated from field: waypoint.module.drill.v1.Calibrate calibrate = 6;
     */
    value: Calibrate;
    case: "calibrate";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<DrillCommand>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "waypoint.module.drill.v1.DrillCommand";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "jog_lift", kind: "message", T: JogLift, oneof: "action" },
    { no: 2, name: "goto_height", kind: "message", T: GotoHeight, oneof: "action" },
    { no: 3, name: "run_auger", kind: "message", T: RunAuger, oneof: "action" },
    { no: 4, name: "stop", kind: "scalar", T: 8 /* ScalarType.BOOL */, oneof: "action" },
    { no: 5, name: "home", kind: "scalar", T: 8 /* ScalarType.BOOL */, oneof: "action" },
    { no: 6, name: "calibrate", kind: "message", T: Calibrate, oneof: "action" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DrillCommand {
    return new DrillCommand().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DrillCommand {
    return new DrillCommand().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DrillCommand {
    return new DrillCommand().fromJsonString(jsonString, options);
  }

  static equals(a: DrillCommand | PlainMessage<DrillCommand> | undefined, b: DrillCommand | PlainMessage<DrillCommand> | undefined): boolean {
    return proto3.util.equals(DrillCommand, a, b);
  }
}

/**
 * @generated from message waypoint.module.drill.v1.JogLift
 */
export class JogLift extends Message<JogLift> {
  /**
   * @generated from field: double velocity_norm = 1;
   */
  velocityNorm = 0;

  constructor(data?: PartialMessage<JogLift>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "waypoint.module.drill.v1.JogLift";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "velocity_norm", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): JogLift {
    return new JogLift().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): JogLift {
    return new JogLift().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): JogLift {
    return new JogLift().fromJsonString(jsonString, options);
  }

  static equals(a: JogLift | PlainMessage<JogLift> | undefined, b: JogLift | PlainMessage<JogLift> | undefined): boolean {
    return proto3.util.equals(JogLift, a, b);
  }
}

/**
 * @generated from message waypoint.module.drill.v1.GotoHeight
 */
export class GotoHeight extends Message<GotoHeight> {
  /**
   * @generated from field: double norm = 1;
   */
  norm = 0;

  constructor(data?: PartialMessage<GotoHeight>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "waypoint.module.drill.v1.GotoHeight";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "norm", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GotoHeight {
    return new GotoHeight().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GotoHeight {
    return new GotoHeight().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GotoHeight {
    return new GotoHeight().fromJsonString(jsonString, options);
  }

  static equals(a: GotoHeight | PlainMessage<GotoHeight> | undefined, b: GotoHeight | PlainMessage<GotoHeight> | undefined): boolean {
    return proto3.util.equals(GotoHeight, a, b);
  }
}

/**
 * @generated from message waypoint.module.drill.v1.RunAuger
 */
export class RunAuger extends Message<RunAuger> {
  /**
   * @generated from field: double throttle = 1;
   */
  throttle = 0;

  constructor(data?: PartialMessage<RunAuger>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "waypoint.module.drill.v1.RunAuger";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "throttle", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RunAuger {
    return new RunAuger().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RunAuger {
    return new RunAuger().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RunAuger {
    return new RunAuger().fromJsonString(jsonString, options);
  }

  static equals(a: RunAuger | PlainMessage<RunAuger> | undefined, b: RunAuger | PlainMessage<RunAuger> | undefined): boolean {
    return proto3.util.equals(RunAuger, a, b);
  }
}

/**
 * @generated from message waypoint.module.drill.v1.Calibrate
 */
export class Calibrate extends Message<Calibrate> {
  /**
   * @generated from field: bool run = 1;
   */
  run = false;

  constructor(data?: PartialMessage<Calibrate>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "waypoint.module.drill.v1.Calibrate";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "run", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Calibrate {
    return new Calibrate().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Calibrate {
    return new Calibrate().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Calibrate {
    return new Calibrate().fromJsonString(jsonString, options);
  }

  static equals(a: Calibrate | PlainMessage<Calibrate> | undefined, b: Calibrate | PlainMessage<Calibrate> | undefined): boolean {
    return proto3.util.equals(Calibrate, a, b);
  }
}

/**
 * ---- wire-compatible mirror of waypoint.v1.ServoState (agent relays raw bytes) ----
 *
 * @generated from message waypoint.module.drill.v1.ServoState
 */
export class ServoState extends Message<ServoState> {
  /**
   * @generated from field: uint32 servo_id = 1;
   */
  servoId = 0;

  /**
   * @generated from field: optional uint32 position_raw = 2;
   */
  positionRaw?: number;

  /**
   * @generated from field: optional sint32 speed_raw = 3;
   */
  speedRaw?: number;

  /**
   * @generated from field: optional sint32 load_raw = 4;
   */
  loadRaw?: number;

  /**
   * @generated from field: optional uint32 current_raw = 5;
   */
  currentRaw?: number;

  /**
   * @generated from field: optional uint32 voltage_deci = 6;
   */
  voltageDeci?: number;

  /**
   * @generated from field: optional uint32 temperature_c = 7;
   */
  temperatureC?: number;

  /**
   * @generated from field: bool moving = 8;
   */
  moving = false;

  /**
   * @generated from field: bool overcurrent_tripped = 9;
   */
  overcurrentTripped = false;

  /**
   * @generated from field: bool ok = 10;
   */
  ok = false;

  constructor(data?: PartialMessage<ServoState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "waypoint.module.drill.v1.ServoState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "servo_id", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "position_raw", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
    { no: 3, name: "speed_raw", kind: "scalar", T: 17 /* ScalarType.SINT32 */, opt: true },
    { no: 4, name: "load_raw", kind: "scalar", T: 17 /* ScalarType.SINT32 */, opt: true },
    { no: 5, name: "current_raw", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
    { no: 6, name: "voltage_deci", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
    { no: 7, name: "temperature_c", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
    { no: 8, name: "moving", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 9, name: "overcurrent_tripped", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 10, name: "ok", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServoState {
    return new ServoState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServoState {
    return new ServoState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServoState {
    return new ServoState().fromJsonString(jsonString, options);
  }

  static equals(a: ServoState | PlainMessage<ServoState> | undefined, b: ServoState | PlainMessage<ServoState> | undefined): boolean {
    return proto3.util.equals(ServoState, a, b);
  }
}

/**
 * ---- backend -> tab: stats at 5 Hz, raw register pairs for the MOTORS card ----
 *
 * @generated from message waypoint.module.drill.v1.DrillStats
 */
export class DrillStats extends Message<DrillStats> {
  /**
   * @generated from field: google.protobuf.Timestamp t = 1;
   */
  t?: Timestamp;

  /**
   * order: lift, auger
   *
   * @generated from field: repeated waypoint.module.drill.v1.ServoState servos = 2;
   */
  servos: ServoState[] = [];

  constructor(data?: PartialMessage<DrillStats>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "waypoint.module.drill.v1.DrillStats";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "t", kind: "message", T: Timestamp },
    { no: 2, name: "servos", kind: "message", T: ServoState, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DrillStats {
    return new DrillStats().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DrillStats {
    return new DrillStats().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DrillStats {
    return new DrillStats().fromJsonString(jsonString, options);
  }

  static equals(a: DrillStats | PlainMessage<DrillStats> | undefined, b: DrillStats | PlainMessage<DrillStats> | undefined): boolean {
    return proto3.util.equals(DrillStats, a, b);
  }
}

/**
 * ---- backend -> tab: home/calibrate progress on the calibration leaf ----
 *
 * @generated from message waypoint.module.drill.v1.CalibrationEvent
 */
export class CalibrationEvent extends Message<CalibrationEvent> {
  /**
   * @generated from field: google.protobuf.Timestamp t = 1;
   */
  t?: Timestamp;

  /**
   * "idle" | "homing" | "run_down" | "run_up" | "done" | "aborted" | "failed"
   *
   * @generated from field: string phase = 2;
   */
  phase = "";

  /**
   * present on "done"
   *
   * @generated from field: optional int64 travel_ticks = 3;
   */
  travelTicks?: bigint;

  /**
   * failure/abort reason, "" otherwise
   *
   * @generated from field: string detail = 4;
   */
  detail = "";

  constructor(data?: PartialMessage<CalibrationEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "waypoint.module.drill.v1.CalibrationEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "t", kind: "message", T: Timestamp },
    { no: 2, name: "phase", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "travel_ticks", kind: "scalar", T: 3 /* ScalarType.INT64 */, opt: true },
    { no: 4, name: "detail", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CalibrationEvent {
    return new CalibrationEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CalibrationEvent {
    return new CalibrationEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CalibrationEvent {
    return new CalibrationEvent().fromJsonString(jsonString, options);
  }

  static equals(a: CalibrationEvent | PlainMessage<CalibrationEvent> | undefined, b: CalibrationEvent | PlainMessage<CalibrationEvent> | undefined): boolean {
    return proto3.util.equals(CalibrationEvent, a, b);
  }
}

